# Generated by Django 4.1 on 2022-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(blank=True, choices=[('d', 'Design'), ('c', 'Ciência da Computação')], max_length=1)),
                ('matricula', models.IntegerField()),
                ('telefone', models.IntegerField(default=0, verbose_name='Numero do telefone verboso')),
            ],
        ),
    ]
