# Generated by Django 4.1.1 on 2022-09-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(choices=[(30, '30 min'), (60, '1h'), (90, '1h30min'), (120, '2h')], default=0),
        ),
    ]
