# Generated by Django 4.1.1 on 2022-09-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
