# Generated by Django 4.0.6 on 2022-09-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_event_adm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pending',
            field=models.IntegerField(default=0),
        ),
    ]
