# Generated by Django 4.1.1 on 2022-09-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_event_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
