# Generated by Django 4.1 on 2022-09-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_event_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='reason',
            field=models.TextField(default=''),
        ),
    ]
