# Generated by Django 4.0.6 on 2022-11-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_reason_event_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(default=None)),
                ('email', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
                ('confirm', models.TextField(default=None)),
            ],
        ),
    ]
