# Generated by Django 4.0.6 on 2022-11-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_userregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='confirm',
        ),
    ]
