# Generated by Django 4.1.1 on 2022-11-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0009_remove_userregister_confirm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
