# Generated by Django 4.1.1 on 2022-11-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0010_delete_userregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateFormUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
