# Generated by Django 4.1.1 on 2022-11-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0011_createformuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateFormUser',
        ),
    ]
